// Databricks notebook source
// MAGIC %md ### NotebookSimilarityRun
// MAGIC 
// MAGIC This notebook executes NotebookSimilarity.
// MAGIC 
// MAGIC   - Arguments include the following:
// MAGIC     - path. The location of the notebook to run (in this case NotebookSimilarity).  It is assumed this notebook is in the same folder as it's run notebook.
// MAGIC     - timeoutSeconds.  Number of seconds to allow for the notebook execution (currently set at 2 hours)
// MAGIC     - indexFilename. Location of the Notebook Discovery Index parquet file generated by NotebookIndex.
// MAGIC     - similarityFilename. Where to place the generated  Notebook Discovery Similarity parquet file  Typically an area mounted on Databricks.
// MAGIC     - overwrite.  Whether the Notebook Discovery Similarity parquet file should be overwritten if it already exists.  'False' will not overwrite. 'True' will overwrite.
// MAGIC     - similarDistance. Max Jaccard distance to use when comparing notebooks
// MAGIC     - vocabSize. Number of unique words (ngrams) you would expect to occur across all of the notebooks that were indexed.
// MAGIC     - ngramSize. Size of the ngram to use when tokenizing and comparing notebooks
// MAGIC     - minDocFreq. Number of notebooks an ngram must occur before it is included in the vocabulary
// MAGIC   

// COMMAND ----------

val rc = dbutils.notebook.run(path="NotebookSimilarity",
                              timeoutSeconds=72000,
                              arguments=Map("indexFilename" -> "/tmp/takaakiyayoidatabrickscom/index", 
                                            "similarityFilename" -> "/tmp/takaakiyayoidatabrickscom/index-similarity",
                                            "overwrite" -> "True",
                                            "similarDistance" -> ".25",
                                            "vocabSize" -> "5000000",
                                            "ngramSize" -> "5",
                                            "minDocFreq" -> "1"))

println(rc)

// COMMAND ----------


